### ISSUE TITLE
osctl cluster create crashes on a MacPro with SIGILL: illegal instruction

### ISSUE THREAD

**Issue by martinborgman** [talos-systems/talos#1934]
Due to an issue in Go 1.14 [37459](https://github.com/golang/go/issues/37459) osctl cluster create crashes with the following output:
```
$ osctl cluster create
validating CIDR and reserving IPs
generating PKI and tokens
SIGILL: illegal instruction
PC=0x1063850 m=9 sigcode=1

goroutine 1 [running]:
runtime.asyncPreempt()
	/toolchain/go/src/runtime/preempt_amd64.s:8 fp=0xc00061e250 sp=0xc00061e248 pc=0x1063850
math/big.nat.montgomery(0xc0004ad8c0, 0x20, 0x46, 0xc0004b4240, 0x20, 0x44, 0xc0004b4240, 0x20, 0x44, 0xc0003f1560, ...)
	/toolchain/go/src/math/big/nat.go:227 +0x1ed fp=0xc00061e2f8 sp=0xc00061e250 pc=0x110d62d
math/big.nat.expNNMontgomery(0xc0004ad8c0, 0x20, 0x46, 0xc0004aac60, 0x20, 0x24, 0xc0004aaa20, 0x20, 0x24, 0xc0003f1560, ...)
	/toolchain/go/src/math/big/nat.go:1435 +0x7a7 fp=0xc00061e5e0 sp=0xc00061e2f8 pc=0x1117167
math/big.nat.expNN(0x0, 0x0, 0x0, 0xc0004aac60, 0x20, 0x24, 0xc0004aaa20, 0x20, 0x24, 0xc0003f1560, ...)
	/toolchain/go/src/math/big/nat.go:1250 +0x95f fp=0xc00061e7a8 sp=0xc00061e5e0 pc=0x11158ff
math/big.nat.probablyPrimeMillerRabin(0xc0003f1560, 0x20, 0x24, 0x15, 0xc297a8c795fbc501, 0x0)
	/toolchain/go/src/math/big/prime.go:106 +0x49c fp=0xc00061e968 sp=0xc00061e7a8 pc=0x111a99c
math/big.(*Int).ProbablyPrime(0xc0002bbe00, 0x14, 0xc00061ea20)
	/toolchain/go/src/math/big/prime.go:78 +0x20c fp=0xc00061e9a8 sp=0xc00061e968 pc=0x111a45c
crypto/rand.Prime(0x2315c20, 0xc000120ed0, 0x800, 0xc0001ceea0, 0xc00061eaf8, 0x110ce8a)
	/toolchain/go/src/crypto/rand/util.go:99 +0x173 fp=0xc00061ea50 sp=0xc00061e9a8 pc=0x12f85b3
crypto/rsa.GenerateMultiPrimeKey(0x2315c20, 0xc000120ed0, 0x2, 0x1000, 0xc000726140, 0x2, 0x7)
	/toolchain/go/src/crypto/rsa/rsa.go:268 +0x167 fp=0xc00061eb90 sp=0xc00061ea50 pc=0x12fe637
crypto/rsa.GenerateKey(...)
	/toolchain/go/src/crypto/rsa/rsa.go:208
github.com/talos-systems/talos/pkg/crypto/x509.RSACertificateAuthority(0xc00061ed10, 0xc000596080, 0x2d7f0e0, 0xc000596080, 0x0)
	/src/pkg/crypto/x509/x509.go:673 +0x68 fp=0xc00061ecc0 sp=0xc00061eb90 pc=0x1dc5e38
github.com/talos-systems/talos/pkg/crypto/x509.NewSelfSignedCertificateAuthority(0xc00061f298, 0x3, 0x3, 0xc0002bbdc0, 0xc4455d52fa3108a0, 0x4606240041de931)
	/src/pkg/crypto/x509/x509.go:218 +0x24c fp=0xc00061f250 sp=0xc00061ecc0 pc=0x1dc408c
github.com/talos-systems/talos/pkg/config/types/v1alpha1/generate.NewKubernetesCA(0xc00030e320, 0x0, 0x0)
	/src/pkg/config/types/v1alpha1/generate/generate.go:163 +0xe1 fp=0xc00061f2c0 sp=0xc00061f250 pc=0x1dcce01
github.com/talos-systems/talos/pkg/config/types/v1alpha1/generate.NewInput(0x21485a7, 0xd, 0xc000148000, 0x15, 0x213f705, 0x6, 0xc000112420, 0x2, 0x2, 0x100be26, ...)
	/src/pkg/config/types/v1alpha1/generate/generate.go:264 +0x38b fp=0xc00061f488 sp=0xc00061f2c0 pc=0x1dcd68b
github.com/talos-systems/talos/pkg/config.NewConfigBundle(0xc000206018, 0x1, 0x1, 0x0, 0x1, 0xc000206018)
	/src/pkg/config/config.go:89 +0x721 fp=0xc00061f5e0 sp=0xc00061f488 pc=0x1e37621
github.com/talos-systems/talos/cmd/osctl/cmd.create(0x234bb00, 0xc000328100, 0x0, 0x0)
	/src/cmd/osctl/cmd/cluster.go:243 +0x961 fp=0xc00061fc28 sp=0xc00061f5e0 pc=0x1e579b1
github.com/talos-systems/talos/cmd/osctl/pkg/helpers.WithCLIContext(0x234bb40, 0xc00011e008, 0x21e82b8, 0x0, 0x0)
	/src/cmd/osctl/pkg/helpers/context.go:44 +0x1bf fp=0xc00061fcd0 sp=0xc00061fc28 pc=0x13985af
github.com/talos-systems/talos/cmd/osctl/cmd.glob..func1(0x2d64b80, 0x2daabe0, 0x0, 0x0, 0x0, 0x0)
	/src/cmd/osctl/cmd/cluster.go:78 +0x45 fp=0xc00061fd08 sp=0xc00061fcd0 pc=0x1e67a95
github.com/spf13/cobra.(*Command).execute(0x2d64b80, 0x2daabe0, 0x0, 0x0, 0x2d64b80, 0x2daabe0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453 fp=0xc00061fde0 sp=0xc00061fd08 pc=0x121e9e3
github.com/spf13/cobra.(*Command).ExecuteC(0x2d69680, 0x2d76a10, 0x2143d30, 0x9)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb fp=0xc00061feb8 sp=0xc00061fde0 pc=0x121f42b
github.com/talos-systems/talos/cmd/osctl/cmd.Execute(0x0, 0x0)
	/src/cmd/osctl/cmd/root.go:65 +0x22e fp=0xc00061ff68 sp=0xc00061feb8 pc=0x1e6456e
main.main()
	/src/cmd/osctl/main.go:18 +0x30 fp=0xc00061ff88 sp=0xc00061ff68 pc=0x1e72b00
runtime.main()
	/toolchain/go/src/runtime/proc.go:203 +0x212 fp=0xc00061ffe0 sp=0xc00061ff88 pc=0x10348d2
runtime.goexit()
	/toolchain/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00061ffe8 sp=0xc00061ffe0 pc=0x1061fe1

goroutine 18 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2d7f480)
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

goroutine 41 [syscall]:
os/signal.signal_recv(0x0)
	/toolchain/go/src/runtime/sigqueue.go:144 +0x96
os/signal.loop()
	/toolchain/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/toolchain/go/src/os/signal/signal.go:127 +0x44

goroutine 26 [select]:
github.com/talos-systems/talos/cmd/osctl/pkg/helpers.WithCLIContext.func1(0xc0000a6300, 0xc00009c240, 0x234bb00, 0xc000328100, 0xc00012c060)
	/src/cmd/osctl/pkg/helpers/context.go:28 +0xfb
created by github.com/talos-systems/talos/cmd/osctl/pkg/helpers.WithCLIContext
	/src/cmd/osctl/pkg/helpers/context.go:27 +0x19f

rax    0xc0004ad8c0
rbx    0x20
rcx    0x1c
rdx    0xdc919de1a9368768
rdi    0xc0004b4240
rsi    0xc0004ad8c0
rbp    0xc00061e2e8
rsp    0xc00061e248
r8     0xc0004b4240
r9     0x6f464918eba15b4b
r10    0xc0004ad9a0
r11    0x20
r12    0x20
r13    0x20
r14    0x20
r15    0xc0004b4240
rip    0x1063850
rflags 0x10283
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by andrewrynhard** [comment]
Thanks @martinborgman! We will look into this ASAP.
