### ISSUE TITLE
Interactive install panics

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#3199]
```
[N] talosctl apply-config --insecure --nodes 192.168.1.223 --interactive
panic: Messages field missing
goroutine 1 [running]:
github.com/talos-systems/talos/pkg/machinery/client.FilterMessages(0x221eb00, 0xc0000a25f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000a25f0)
	/src/pkg/machinery/client/reply.go:56 +0xc45
github.com/talos-systems/talos/pkg/machinery/client.(*Client).Disks(0xc000870ab0, 0x2747560, 0xc000052080, 0x0, 0x0, 0x0, 0x1a, 0x1, 0xd)
	/src/pkg/machinery/client/client.go:412 +0xb8
github.com/talos-systems/talos/internal/pkg/tui/installer.(*Connection).Disks(...)
	/src/internal/pkg/tui/installer/connection.go:62
github.com/talos-systems/talos/internal/pkg/tui/installer.NewState(0x2747520, 0xc0008e1880, 0xc000114ae0, 0xc0000a2320, 0xc000114e40, 0xc000de3801, 0x0)
	/src/internal/pkg/tui/installer/state.go:69 +0x3a6
github.com/talos-systems/talos/internal/pkg/tui/installer.(*Installer).init(0xc000114ae0, 0xc0000a2320, 0x50, 0x7f135e8d0108)
	/src/internal/pkg/tui/installer/installer.go:165 +0x195
github.com/talos-systems/talos/internal/pkg/tui/installer.(*Installer).Run(0xc000114ae0, 0xc0000a2320, 0x0, 0x0)
	/src/internal/pkg/tui/installer/installer.go:89 +0x3b4
github.com/talos-systems/talos/cmd/talosctl/cmd/talos.glob..func1.2(0x2747560, 0xc000052080, 0xc000870ab0, 0x2, 0x2)
	/src/cmd/talosctl/cmd/talos/apply-config.go:134 +0x110
github.com/talos-systems/talos/cmd/talosctl/cmd/talos.glob..func1.1(0xc000de6d20, 0x0, 0x0)
	/src/cmd/talosctl/cmd/talos/apply-config.go:95 +0x3f2
github.com/talos-systems/talos/cmd/talosctl/cmd/talos.glob..func1(0x36877a0, 0xc0008e15c0, 0x0, 0x4, 0x0, 0x0)
	/src/cmd/talosctl/cmd/talos/apply-config.go:101 +0xc2
github.com/spf13/cobra.(*Command).execute(0x36877a0, 0xc0008e1580, 0x4, 0x4, 0x36877a0, 0xc0008e1580)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x36845c0, 0x36a60b0, 0x2403818, 0x9)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/talos-systems/talos/cmd/talosctl/cmd.Execute(0x0, 0x0)
	/src/cmd/talosctl/cmd/root.go:42 +0x235
main.main()
	/src/cmd/talosctl/main.go:18 +0x33
```

**Comment by tiger-seo** [comment]
same for me.  i have followed instruction from https://www.talos.dev/docs/v0.8/single-board-computers/rpi_4/ for RPI4 then on the other rpi (RPI3) i downloaded talosctl for armv7 and got same message as issue reporter:

```
$ talosctl apply-config --insecure --interactive --nodes 192.168.1.221
panic: Messages field missing

goroutine 1 [running]:
github.com/talos-systems/talos/pkg/machinery/client.FilterMessages(0x15f58b8, 0x411e750, 0x0, 0x0, 0x0, 0x0, 0x0, 0x411e750)
        /src/pkg/machinery/client/reply.go:56 +0x99c
github.com/talos-systems/talos/pkg/machinery/client.(*Client).Disks(0x411e450, 0x198c640, 0x410e010, 0x0, 0x0, 0x0, 0x1a, 0x4141b80, 0x0)
        /src/pkg/machinery/client/client.go:393 +0x88
github.com/talos-systems/talos/internal/pkg/tui/installer.(*Connection).Disks(...)
        /src/internal/pkg/tui/installer/connection.go:62
github.com/talos-systems/talos/internal/pkg/tui/installer.NewState(0x198c620, 0x42587c0, 0x411e570, 0x411e5a0, 0x411e5d0, 0x4141a01, 0x0)
        /src/internal/pkg/tui/installer/state.go:69 +0x2d8
github.com/talos-systems/talos/internal/pkg/tui/installer.(*Installer).init(0x411e570, 0x411e5a0, 0x1f, 0x28)
        /src/internal/pkg/tui/installer/installer.go:165 +0x140
github.com/talos-systems/talos/internal/pkg/tui/installer.(*Installer).Run(0x411e570, 0x411e5a0, 0x0, 0x0)
        /src/internal/pkg/tui/installer/installer.go:89 +0x2dc
github.com/talos-systems/talos/cmd/talosctl/cmd/talos.glob..func1.2(0x198c640, 0x410e010, 0x411e450, 0x2, 0x2)
        /src/cmd/talosctl/cmd/talos/apply-config.go:133 +0xc4
github.com/talos-systems/talos/cmd/talosctl/cmd/talos.glob..func1.1(0x4377890, 0x0, 0x0)
        /src/cmd/talosctl/cmd/talos/apply-config.go:94 +0x3e8
github.com/talos-systems/talos/cmd/talosctl/cmd/talos.glob..func1(0x24dc120, 0x41bd640, 0x0, 0x4, 0x0, 0x0)
        /src/cmd/talosctl/cmd/talos/apply-config.go:100 +0xa4
github.com/spf13/cobra.(*Command).execute(0x24dc120, 0x41bd3e0, 0x4, 0x4, 0x24dc120, 0x41bd3e0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x340
github.com/spf13/cobra.(*Command).ExecuteC(0x24da830, 0x24ea8b0, 0x16ea459, 0x9)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x274
github.com/talos-systems/talos/cmd/talosctl/cmd.Execute(0x0, 0x0)
        /src/cmd/talosctl/cmd/root.go:42 +0x1bc
main.main()
        /src/cmd/talosctl/main.go:18 +0x24

```
