### ISSUE TITLE
grpc-js sends more than one tls certificate

### ISSUE THREAD

**Issue by hall** [talos-systems/talos#4910]
### Description

I'm writing a small gRPC client in node and have come across what appears to be incompatible behavior. The authz injector [throws an error](https://github.com/talos-systems/talos/blob/446972f2113ada8e6c511ce56f630ec170ef0f26/pkg/grpc/middleware/authz/injector.go#L86-L88) if it receives more than one certificate but the [grpc-js](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js) client (or node itself in [the call to](https://github.com/grpc/grpc-node/blob/c1d68a00aceb552a49ffab1bba502896fc9d1b46/packages/grpc-js/src/channel-credentials.ts#L134-L139) the [`createSecureContext`](https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions) method, I'm not sure) sends _both_ the ca (subject: `talos`) and client cert (subject: `os:admin`) such that any call returns this error
```
$ node test.js
Error: 13 INTERNAL: expected one certificate, got 2
```

Where `test.js` is this (fairly) minimal working example, pointing at an existing set of protobuf definitions (e.g., from the talos repo).

```js
const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const yaml = require('js-yaml');
const fs = require("fs");
const path = require("path");
const os = require("os");

// path to protobuf definitions
const protos = path.join(os.homedir(), "src", "github.com", "talos-systems", "talos", "api");

const file = path.join(os.homedir(), ".talos", "config");
const cfg = yaml.load(fs.readFileSync(file));
let config = cfg.contexts[cfg.context];

// node doesn't seem to like the ED25519 string in the PEM start/end lines
config.key = Buffer.from(Buffer.from(config.key, 'base64').toString()
    .replaceAll("ED25519 ", "")).toString('base64')

const creds = grpc.ChannelCredentials.createSsl(
    Buffer.from(config.ca, 'base64'),
    Buffer.from(config.key, 'base64'),
    Buffer.from(config.crt, 'base64'),
)

let def = protoLoader.loadSync(`${protos}/machine/machine.proto`,
    { includeDirs: [protos, path.join(protos, "vendor")] });
let machine = grpc.loadPackageDefinition(def).machine;
let client = new machine.MachineService(`${config.endpoints[0]}:50000`, creds);

client.Version({}, (error, response) => {
    if (error) {
        console.log(error)
    } else {
        console.log(JSON.stringify(response, null, 4))
    }
})
```

I was able to get the client to work by commenting out that `panic` (effectively forcing talos to pick a cert from the list) but just wanted to verify what the correct behavior _should be_ before opening any PRs.

 - Can talos reliably take the first/last certificate in the list? I'm not certain whether it's guaranteed to be ordered from

       ca -> intermediate  -> . . . -> client

 - Or should grpc-js (or node, if possible) not being sending the full cert chain?

### Logs

`apid` logs during a gRPC call.

```
$ _out/talosctl-linux-amd64 -n 172.20.0.2 logs apid
172.20.0.2: 2022/02/02 03:11:51.374838 factory.go:127: panic: expected one certificate, got 2
172.20.0.2: goroutine 144 [running]:
172.20.0.2: runtime/debug.Stack()
172.20.0.2:     /toolchain/go/src/runtime/debug/stack.go:24 +0x65
172.20.0.2: github.com/talos-systems/talos/pkg/grpc/factory.recoveryHandler.func1({0x26355e0, 0xc000386eb0})
172.20.0.2:     /src/pkg/grpc/factory/factory.go:127 +0x49
172.20.0.2: github.com/grpc-ecosystem/go-grpc-middleware/recovery.WithRecoveryHandler.func1.1({0x2cd09f1, 0x0}, {0x26355e0, 0xc000386eb0})
172.20.0.2:     /.cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/options.go:33 +0x2d
172.20.0.2: github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x32564e8, 0xc000a22b10}, {0x26355e0, 0xc000386eb0}, 0x0)
172.20.0.2:     /.cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:61 +0x36
172.20.0.2: github.com/grpc-ecosystem/go-grpc-middleware/recovery.StreamServerInterceptor.func1.1()
172.20.0.2:     /.cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:47 +0x8f
172.20.0.2: panic({0x26355e0, 0xc000386eb0})
172.20.0.2:     /toolchain/go/src/runtime/panic.go:1038 +0x215
172.20.0.2: github.com/talos-systems/talos/pkg/grpc/middleware/authz.(*Injector).extractRoles(0xc0002c5ae0, {0x32564e8, 0xc000a22b10})
172.20.0.2:     /src/pkg/grpc/middleware/authz/injector.go:89 +0x4d4
172.20.0.2: github.com/talos-systems/talos/pkg/grpc/middleware/authz.(*Injector).StreamInterceptor.func1({0x0, 0x0}, {0x327ef10, 0xc00017b980}, 0x0, 0xc0002c5b40)
172.20.0.2:     /src/pkg/grpc/middleware/authz/injector.go:130 +0x65
172.20.0.2: github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x0, 0x0}, {0x327ef10, 0xc00017b980})
172.20.0.2:     /.cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
172.20.0.2: github.com/grpc-ecosystem/go-grpc-middleware/recovery.StreamServerInterceptor.func1({0x0, 0x0}, {0x327ef10, 0xc00017b980}, 0xc000a6aa90, 0x4897f7)
172.20.0.2:     /.cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:51 +0xb4
172.20.0.2: github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x0, 0x0}, {0x327ef10, 0xc00017b980})
172.20.0.2:     /.cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
172.20.0.2: github.com/talos-systems/talos/pkg/grpc/middleware/log.(*Middleware).StreamInterceptor.func1({0x0, 0x0}, {0x327ef10, 0xc00017b980}, 0xc0006dcc30, 0xc0002bc040)
172.20.0.2:     /src/pkg/grpc/middleware/log/log.go:88 +0xad
172.20.0.2: github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1({0x0, 0x0}, {0x327ef10, 0xc00017b980})
172.20.0.2:     /.cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:49 +0x3a
172.20.0.2: github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1({0x0, 0x0}, {0x327ef10, 0xc00017b980}, 0x2582cc0, 0xc000386ea0)
172.20.0.2:     /.cache/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:58 +0xbf
172.20.0.2: google.golang.org/grpc.(*Server).processStreamingRPC(0xc0006ee1c0, {0x329b498, 0xc00070b1e0}, 0xc000664900, 0x0, 0xc00004dcc0, 0x0)
172.20.0.2:     /.cache/mod/google.golang.org/grpc@v1.44.0/server.go:1547 +0xe9a
172.20.0.2: google.golang.org/grpc.(*Server).handleStream(0xc0006ee1c0, {0x329b498, 0xc00070b1e0}, 0xc000664900, 0x0)
172.20.0.2:     /.cache/mod/google.golang.org/grpc@v1.44.0/server.go:1626 +0x99c
172.20.0.2: google.golang.org/grpc.(*Server).serveStreams.func1.2()
172.20.0.2:     /.cache/mod/google.golang.org/grpc@v1.44.0/server.go:921 +0x98
172.20.0.2: created by google.golang.org/grpc.(*Server).serveStreams.func1
172.20.0.2:     /.cache/mod/google.golang.org/grpc@v1.44.0/server.go:919 +0x294
172.20.0.2: 2022/02/02 03:11:51.374868 log.go:98: Internal [/machine.MachineService/Version] 135.781µs stream rpc error: code = Internal desc = expected one certificate, got 2 (:authority=172.20.0.2:50000;accept-encoding=identity;content-type=application/grpc;grpc-accept-encoding=identity,deflate,gzip;user-agent=grpc-node-js/1.5.3)
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]

      $ _out/talosctl-linux-amd64 version -n 172.20.0.2
      Client:
              Tag:         v0.15.0-alpha.1-24-g7f0b3aae
              SHA:         7f0b3aae
              Built:       
              Go version:  go1.17.6
              OS/Arch:     linux/amd64
      Server:
              NODE:        172.20.0.2
              Tag:         v0.15.0-alpha.1-24-g7f0b3aae-dirty
              SHA:         7f0b3aae-dirty
              Built:       
              Go version:  go1.17.6
              OS/Arch:     linux/amd64
              Enabled:     RBAC

- Kubernetes version: [`kubectl version --short`]
- Platform: tested on `raspberrypi` and the `qemu` dev build

**Comment by smira** [comment]
thanks, this sounds like a bug we should fix. We'll see what we can do here to skip the intermediate certificates sent.
